excerpt_separator: <!-- more -->
url: http://dankuck.github.io
name: dankuck
description: "I'm dankuck and I write what you read."
markdown: kramdown
azntag: "dankuck-20"
google_tracking_id: "UA-52383063-1"