excerpt_separator: <!-- more -->
url: http://www.dankuck.com
name: dankuck
description: "I'm Dan Kuck and I write what you read."
markdown: kramdown
azntag: "dankuck-20"
google_tracking_id: "UA-52383063-1"
